#!/bin/bash

sed "s/changehost/${VARNISH_BACKEND_IP}/i" -i /etc/varnish/default.vcl
sed "s/changeport/${VARNISH_BACKEND_PORT}/i" -i /etc/varnish/default.vcl

# Start varnish and log
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}
varnishlog
